export const USER_LOGGED_IN = 'userLoggedIn'
export const ERROR_ON_LOGIN = 'errorOnLogin'
export const USER_LOGGED_OUT = 'userLoggedOut'
export const SHOW_AUTH_DIALOG = 'showAuthDialog'
export const HIDE_AUTH_DIALOG = 'hideAuthDialog'